// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrjL8vha5-5xeS1VfqhwIfDatOyIADSLI',
    appId: '1:118742994721:web:34111ab4ba10e5b3bc3860',
    messagingSenderId: '118742994721',
    projectId: 'two-m-ke',
    authDomain: 'two-m-ke.firebaseapp.com',
    databaseURL: 'https://two-m-ke-default-rtdb.firebaseio.com',
    storageBucket: 'two-m-ke.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCakWdedga9xANTAq2EfAYvvFTkgDHBARI',
    appId: '1:118742994721:android:c20bca8e36d3090bbc3860',
    messagingSenderId: '118742994721',
    projectId: 'two-m-ke',
    databaseURL: 'https://two-m-ke-default-rtdb.firebaseio.com',
    storageBucket: 'two-m-ke.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQIYTdYMV8LVNUJViZz_fbeaar_C4NXv4',
    appId: '1:118742994721:ios:092e62e0a837bb0fbc3860',
    messagingSenderId: '118742994721',
    projectId: 'two-m-ke',
    databaseURL: 'https://two-m-ke-default-rtdb.firebaseio.com',
    storageBucket: 'two-m-ke.firebasestorage.app',
    iosBundleId: 'com.twom.vendor',
  );

}